name: PR Review

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  ai-review:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/reusable-ai-review.yml
    permissions:
      contents: read
      pull-requests: write
      issues: write
      statuses: write
    secrets: inherit